zooniverse/designator

config/dev.exs, config/prod.exs
~~Couldn't test locally as the docker containers built but wouldn't start. Happy to do something else if i can get this tested instead of testing via staging deploy.~~
Tested on the running container and this works, seems the default fallback is 5 somehow if the string is passed, 10 if null...weird.
=> ensure the pool_size option is an integer

README.md, lib/designator/random.ex, lib/designator/random_stream.ex, lib/designator/selection.ex, lib/designator/subject_stream.ex, test/designator/random_stream_test.exs, test/designator/random_test.exs, test/designator/selection_test.exs
The SubjectStream now detects when it has sent out all subject_ids in the
set, and will signal an end-of-stream down the pipeline. This means that
reading 10 subjects from a stream that can only possibly emit 5, will finish
rather than hang forever.
=> Replace infinite stream with one that finishes when all subjects are sent

lib/designator/subject_set_cache.ex
This would keep reloading subject sets that have no subjects left. Originally intended as a safe-guard, but now that stuff expires, this is not needed.
=> Remove needless constant reloads for workflows

README.md, lib/designator/selection.ex, test/designator/selection_test.exs, web/controllers/workflow_controller.ex
Allow the API to accept a `subject_set_id` query param and filter restrict the selected subject to the subject set matching the param, if valid for this workflow.
=> Add per subject set selection

.dockerignore, .gitignore, README.md, lib/designator/user_cache.ex, test/controllers/user_controller_test.exs, test/designator/selection_test.exs, web/controllers/helpers.ex, web/controllers/user_controller.ex, web/controllers/workflow_controller.ex, web/router.ex, web/web.ex
Closes #85 by adding an API to update a user's subjects `seen_ids` list
Allow a cached user to have their `seen_ids` updated via PUT api endpoints that accepts JSON encoded data payloads:
1. `/api/users/#{user_id}/add_seen_subjects`
+ accepts `{ workflow_id: ${workflow_id}, subject_ids: [1,2,3]}`
0. `/api/users/#{user_id}/add_seen_subject`
+ accepts `{ workflow_id: ${workflow_id}, subject_id: 4}`
The implementation is similar to the existing reliance on the ConCache ETS memory store, i.e the workflow `do_remove` at `/api/workflows/:id/remove` which wrapped the RecentlyRetired ConCache store.
It will raise an error if the workflow_id is not a string or integer that can be cast to an integer. It will check and cast all subject_ids to valid integers before storing in the user cache …
=> Add API to allow updates to a user's seen subject ids for a workflow

README.md, lib/designator/selection.ex, test/designator/selection_test.exs
Fixes #87 
Non-logged in users have no seen subjects and thus will always trigger the first tier of training on configured workflows. Instead, this PR will change the behaviour to ignore any training directives for users we have no data on.
=> skip training directives for non-logged in users

config/config.exs, kubernetes/deployment-staging.tmpl
The pod is failing to start because `** (Code.LoadError) could not load /app/config/staging.exs`. This file doesn't exist on the current staging EC2 instance, either, so I'm not sure what it's supposed to hold. It doesn't exist on S3 and doesn't seem to be being built by any of the designator scripts in the ops repo.
Config options are now being loaded in as env vars via k8s deploy template, but clearly this isn't building without that file loading (presumably the test.exs file for the CI checks). Not sure what's up here yet but I'll have to come back to this later.
=> Use prod env in staging in k8s also

kubernetes/deployment-staging.tmpl
After merging the last one (https://github.com/zooniverse/designator/pull/93), I started to get yelled at about a missing $PORT env var. This system env var exists on both the prod and staging ec2 instances and is the same on both: `4000`. I can't precisely tell where it's coming from in the current builds but adding it to the template should work.
=> Add PORT env var

kubernetes/deployment-staging.tmpl
linked to #97  
use port 80 (app default) for container runtime in k8s. Also remove app signal env vars, it's not in use
=> use port 80 and cleanup env vars

Dockerfile, Jenkinsfile, config/config.exs, docker-compose.yml, web/controllers/root_controller.ex, web/router.ex, web/views/root_view.ex
add status page on root `/` path with git revision. the git revision will be injected at build time via jenkins, no more git dep in the repo or reading / caching files for this info, it's a straight up env var now 🎉
=> add root status route with git revision

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Allow production more RAM / CPU, match the old ec2 instance specs (4GB RAM & 2vcpus) to avoid the OOM errors and pod restarts, via `kubectl describe pod designator-production-app-56d47b487c-5kvb5`
```
State:          Running
Started:      Tue, 02 Jun 2020 08:06:06 +0100
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Mon, 01 Jun 2020 21:14:39 +0100
Finished:     Tue, 02 Jun 2020 08:06:05 +0100
Ready:          True
Restart Count:  8
```
Also allow staging more RAM to avoid OOM errors and pod restarts on this service.
=> K8s limits increase RAM & CPU

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Add readiness probe that is used for rolling deployment. I locally tested the app boot times on production image and it's <5s. 
>but the existence of the readiness probe in the spec means that the Pod will start without receiving any traffic and only start receiving traffic after the probe starts succeeding. If your Container needs to work on loading large data, configuration files, or migrations during startup, specify a readiness probe.
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-readiness-probe
noting that both the live and readiness probes will hit the container ever 10s (default) https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes
=> K8s readiness probe

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Request RAM limit up front and allow prod cpu to burst to 2vcpus
prod ram for current normal load is ~500MB, allowing increase up to ~3GB will provide headroom for larger numbers of concurrent user selections. Allowing the CPU to burst to 2vcpus will also add headroom for scaling events.
=> Modify k8s RAM & CPU limits

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
this PR modifies the 
- staging service pod to request less RAM (frees up 100Mi on the node) for other pod scheduling
- production service pod to request a lot less RAM and less CPU (allow it to grow over time)
Currently the pods (measure after ~60days of service) are using much less in the wild.
```
$ kubectl top pod --containers | grep designator
designator-production-app-57f9cfd984-5x5mk                 designator-production-app        11m          269Mi           
designator-staging-app-5b46778788-kfk9q                    designator-staging-app                  1m            86Mi 
``
Freeing up the request RAM means the other pods can schedule and share the node resources.
When a request is made and a pod is scheduled this compute resource request (CPU/RAM) is allocated for the pod …
```
=> update designator service K8s resources usage

mix.exs, test/support/cache_case.ex, web/models/user_seen_subject.ex
Warnings as outlined in GA actions output and from `mix test`, this PR removes the following
- unused function params
- unused tag context in test setup
- quoted keywords
=> Fix compiler warnings

lib/designator/selection.ex
avoid deprecated lang features - make sure we can correctly report the stacktrace by throwing an artifical run time error if we hit a task timeout
Reported in https://github.com/zooniverse/designator/pull/121/files
> System.stacktrace/0 outside of rescue/catch clauses is deprecated. If you want to support only Elixir v1.7+, you must access __STACKTRACE__ inside a rescue/catch. If you want to support earlier Elixir versions, move System.stacktrace/0 inside a rescue/catch
=> use System.stacktrace inside rescue / catch

lib/designator/selection.ex, lib/designator/subject_set_cache.ex, lib/designator/workflow_cache.ex, test/designator/selection_test.exs, test/designator/workflow_cache_test.exs, test/models/workflow_test.exs, web/models/workflow.ex
closes #91 
This PR changes the way per subject set selection works in Designator. Currently we allow filtering on subject sets even if the workflow isn't grouped. 
This PR will now ensure ensure we respect `subject_set_id` param for grouped workflows and do not return data in other linked sets. For non grouped workflows this PR will ignore the `subject_set_id` param and select from all sets which is the current behaviour if the set is not found.
Thus a workflow must have grouped turned on to access per subject_set selection behaviours.
=> Respect workflow.grouped setting when selection by subject_set

web/router.ex
closes #119 - This PR avoid reporting UnknownRoute errors (404s) while still reporting other request errors to Rollbar as normal.
Based on https://github.com/slashdotdash/til/blob/master/elixir/rollbar-exception-reporting-for-phoenix.md#rollbar-exception-reporting-for-phoenix
=> ignore routing errors

README.md, lib/designator/selection.ex, test/designator/selection_test.exs
closes https://github.com/zooniverse/panoptes/issues/3789
avoid skipping past what has been recently seen in the user cache as priority workflows want to ensure folks see the head of the priority queue in order at all times.
=> Skip recent seen filtering for priority workflows

.github/workflows/deploy_staging.yml, Jenkinsfile
Builds/pushes a new image to GHCR, tags with latest, and deploys to staging. Does not perform any migration, does this happen automatically anywhere now? We obviously haven't had to do one in a while (see also eduapi & caesar) but there's no Jenkins job or hook and it seems like it'd have to be manual from a pod. I can build a k8s job to run whatever the appropriate `mix` command is if that'd be useful.
=> Deploy staging with an Action

Dockerfile
Designator's RootController pulls the revision out of the system's env vars. This sets that env var in the Dockerfile from the commit_id.txt file that the build/push action creates. It sets a default if the file is missing, so that the file isn't required for development.
=> Use commit_id.txt for revision & keep env var

Dockerfile, start.sh
Reading from a file and conditionally setting different env vars isn't ideal for a Dockerfile, since the env vars from RUN commands aren't persisted across layers. Instead, just run a couple lines in the start script to read from the file and set a default if it's missing.
=> Set $REVISION in start script
